object PageLoginSupervisor: TPageLoginSupervisor
  Left = 0
  Top = 0
  Align = alClient
  AlphaBlend = True
  AlphaBlendValue = 240
  BorderStyle = bsNone
  ClientHeight = 710
  ClientWidth = 1190
  Color = clBackground
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OnClose = FormClose
  OnKeyDown = FormKeyDown
  OnShow = FormShow
  TextHeight = 14
  object pnlContainer: TPanel
    AlignWithMargins = True
    Left = 216
    Top = 128
    Width = 289
    Height = 273
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    BevelOuter = bvNone
    Color = clWhite
    ParentBackground = False
    TabOrder = 0
    object pnlLogar: TPanel
      Left = 0
      Top = 0
      Width = 289
      Height = 273
      Align = alClient
      BevelOuter = bvNone
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentBackground = False
      ParentFont = False
      TabOrder = 0
      ExplicitHeight = 233
      object pnlTitLogin: TPanel
        Left = 0
        Top = 0
        Width = 289
        Height = 41
        Align = alTop
        BevelOuter = bvNone
        Caption = 'Permiss'#227'o Supervisor/Gerente'
        TabOrder = 0
      end
      object pnlUsuario: TPanel
        AlignWithMargins = True
        Left = 5
        Top = 46
        Width = 279
        Height = 60
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Align = alTop
        BevelOuter = bvNone
        TabOrder = 1
        object lblUsuario: TLabel
          Left = 0
          Top = 0
          Width = 279
          Height = 19
          Align = alTop
          Caption = 'Usu'#225'rio'
          ExplicitWidth = 54
        end
        object shpLogin: TShape
          AlignWithMargins = True
          Left = 0
          Top = 22
          Width = 279
          Height = 35
          Margins.Left = 0
          Margins.Right = 0
          Align = alClient
          Shape = stRoundRect
          ExplicitLeft = 80
          ExplicitTop = 24
          ExplicitWidth = 65
          ExplicitHeight = 65
        end
        object edtUsuario: TEdit
          AlignWithMargins = True
          Left = 3
          Top = 29
          Width = 273
          Height = 21
          Margins.Top = 10
          Margins.Bottom = 10
          Align = alClient
          BorderStyle = bsNone
          TabOrder = 0
        end
      end
      object pnlSenha: TPanel
        AlignWithMargins = True
        Left = 5
        Top = 116
        Width = 279
        Height = 60
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        Align = alTop
        BevelOuter = bvNone
        TabOrder = 2
        object lblSenha: TLabel
          Left = 0
          Top = 0
          Width = 279
          Height = 19
          Align = alTop
          Caption = 'Senha'
          ExplicitWidth = 43
        end
        object shpSenha: TShape
          AlignWithMargins = True
          Left = 0
          Top = 22
          Width = 279
          Height = 35
          Margins.Left = 0
          Margins.Right = 0
          Align = alClient
          Shape = stRoundRect
          ExplicitLeft = 80
          ExplicitTop = 24
          ExplicitWidth = 65
          ExplicitHeight = 65
        end
        object edtSenha: TEdit
          AlignWithMargins = True
          Left = 3
          Top = 29
          Width = 273
          Height = 21
          Margins.Top = 10
          Margins.Bottom = 10
          Align = alClient
          BorderStyle = bsNone
          PasswordChar = '*'
          TabOrder = 0
        end
      end
      object pnlBtns: TPanel
        Left = 0
        Top = 232
        Width = 289
        Height = 41
        Align = alBottom
        BevelOuter = bvNone
        TabOrder = 3
        ExplicitTop = 192
        object pnlBtnCancelar: TPanel
          Left = 0
          Top = 0
          Width = 145
          Height = 41
          Align = alLeft
          BevelOuter = bvNone
          Padding.Left = 5
          TabOrder = 0
          object shpBtnCancelar: TShape
            Left = 5
            Top = 0
            Width = 140
            Height = 41
            Align = alClient
            Brush.Color = clSilver
            Pen.Style = psClear
            Shape = stRoundRect
            ExplicitLeft = 112
            ExplicitTop = -8
            ExplicitWidth = 65
            ExplicitHeight = 65
          end
          object btnCancelar: TSpeedButton
            Left = 5
            Top = 0
            Width = 140
            Height = 41
            Align = alClient
            Caption = 'Cancelar'
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -19
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ExplicitWidth = 139
          end
        end
        object pnlBtnConfirmar: TPanel
          Left = 145
          Top = 0
          Width = 144
          Height = 41
          Align = alClient
          BevelOuter = bvNone
          Padding.Right = 5
          TabOrder = 1
          object shpBtnConfirmar: TShape
            Left = 0
            Top = 0
            Width = 139
            Height = 41
            Align = alClient
            Brush.Color = clPurple
            Pen.Style = psClear
            Shape = stRoundRect
            ExplicitLeft = 5
            ExplicitWidth = 279
          end
          object btnConfirmar: TSpeedButton
            Left = 0
            Top = 0
            Width = 139
            Height = 41
            Align = alClient
            Caption = 'Confirmar'
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWhite
            Font.Height = -19
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
          end
        end
      end
    end
  end
end
