object PageAberturaCaixa: TPageAberturaCaixa
  Left = 0
  Top = 0
  AlphaBlend = True
  AlphaBlendValue = 240
  BorderStyle = bsNone
  ClientHeight = 710
  ClientWidth = 1190
  Color = clBackground
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OnClose = FormClose
  OnKeyDown = FormKeyDown
  OnResize = FormResize
  TextHeight = 16
  object pnlContainerAbertura: TPanel
    AlignWithMargins = True
    Left = 280
    Top = 112
    Width = 593
    Height = 409
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    BevelOuter = bvNone
    ParentBackground = False
    TabOrder = 0
    object pnlTitulo: TPanel
      Left = 0
      Top = 0
      Width = 593
      Height = 53
      Align = alTop
      BevelOuter = bvNone
      Caption = 'Abertura de Caixa'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clPurple
      Font.Height = -33
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object pnlAviso: TPanel
      Left = 0
      Top = 53
      Width = 593
      Height = 24
      Align = alTop
      BevelOuter = bvNone
      Caption = 'Informe os valores dispon'#237'veis para iniciar a Abertura'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 6708056
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object pnlInfo: TPanel
      AlignWithMargins = True
      Left = 3
      Top = 80
      Width = 587
      Height = 326
      Align = alClient
      BevelOuter = bvNone
      Padding.Left = 150
      Padding.Top = 100
      Padding.Right = 150
      Padding.Bottom = 100
      TabOrder = 2
      object pnlInfoCaixa: TPanel
        Left = 150
        Top = 100
        Width = 287
        Height = 126
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 0
        object pnlBtnAbrirCaixa: TPanel
          Left = 0
          Top = 66
          Width = 287
          Height = 60
          Align = alClient
          BevelOuter = bvNone
          Padding.Top = 2
          Padding.Bottom = 2
          TabOrder = 0
          object shpBtnAbrirCaixa: TShape
            Left = 0
            Top = 2
            Width = 287
            Height = 56
            Align = alClient
            Brush.Color = clPurple
            Pen.Style = psClear
            Shape = stRoundRect
            ExplicitLeft = 112
            ExplicitTop = 0
            ExplicitWidth = 65
            ExplicitHeight = 65
          end
          object btnAbrirCaixa: TSpeedButton
            Left = 0
            Top = 2
            Width = 287
            Height = 56
            Align = alClient
            Caption = 'Abrir Caixa'
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWhite
            Font.Height = -33
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            OnClick = btnAbrirCaixaClick
            ExplicitLeft = 136
            ExplicitTop = 24
            ExplicitWidth = 23
            ExplicitHeight = 22
          end
        end
        object pnlDispCaixa: TPanel
          Left = 0
          Top = 0
          Width = 287
          Height = 66
          Align = alTop
          BevelOuter = bvNone
          TabOrder = 1
          object pnlTituloDispCaixa: TPanel
            Left = 0
            Top = 0
            Width = 287
            Height = 20
            Align = alTop
            BevelOuter = bvNone
            Caption = 'Dispon'#237'vel no Caixa'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6708056
            Font.Height = -16
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            TabOrder = 0
          end
          object pnlEdtDispCaixa: TPanel
            Left = 0
            Top = 20
            Width = 287
            Height = 46
            Align = alClient
            BevelOuter = bvNone
            TabOrder = 1
            object shpEdtDispCaixa: TShape
              Left = 0
              Top = 0
              Width = 287
              Height = 46
              Align = alClient
              Pen.Style = psClear
              Shape = stRoundRect
              ExplicitLeft = 112
              ExplicitTop = -8
              ExplicitWidth = 65
              ExplicitHeight = 65
            end
            object edtValorSuprimento: TEdit
              AlignWithMargins = True
              Left = 3
              Top = 3
              Width = 281
              Height = 40
              Align = alClient
              Alignment = taCenter
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -33
              Font.Name = 'Tahoma'
              Font.Style = [fsBold]
              ParentFont = False
              TabOrder = 0
              Text = 'R$ 0,00'
            end
          end
        end
      end
    end
  end
end
