object PageFechamentoCaixa: TPageFechamentoCaixa
  Left = 0
  Top = 0
  AlphaBlend = True
  AlphaBlendValue = 240
  BorderStyle = bsNone
  ClientHeight = 710
  ClientWidth = 1190
  Color = clBackground
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Tahoma'
  Font.Style = []
  KeyPreview = True
  OnKeyDown = FormKeyDown
  OnResize = FormResize
  TextHeight = 16
  object pnlContainerFechamento: TPanel
    AlignWithMargins = True
    Left = 280
    Top = 112
    Width = 593
    Height = 474
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    BevelOuter = bvNone
    ParentBackground = False
    TabOrder = 0
    object pnlTitulo: TPanel
      Left = 0
      Top = 0
      Width = 593
      Height = 53
      Align = alTop
      BevelOuter = bvNone
      Caption = 'Confer'#234'ncia de Caixa'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clPurple
      Font.Height = -33
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
    end
    object pnlAviso: TPanel
      Left = 0
      Top = 53
      Width = 593
      Height = 24
      Align = alTop
      BevelOuter = bvNone
      Caption = 'Informe os valores recebidos no caixa'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 6708056
      Font.Height = -13
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
    end
    object pnlInfo: TPanel
      AlignWithMargins = True
      Left = 3
      Top = 80
      Width = 587
      Height = 391
      Align = alClient
      BevelOuter = bvNone
      Padding.Left = 10
      Padding.Top = 20
      Padding.Right = 10
      Padding.Bottom = 10
      TabOrder = 2
      ExplicitLeft = 0
      ExplicitTop = 83
      ExplicitHeight = 326
      object pnlFuncoes: TPanel
        Left = 10
        Top = 20
        Width = 567
        Height = 61
        Align = alTop
        BevelOuter = bvNone
        TabOrder = 0
        object pnlBtnAdicionar: TPanel
          Left = 506
          Top = 0
          Width = 61
          Height = 61
          Align = alRight
          BevelOuter = bvNone
          TabOrder = 0
          ExplicitLeft = 382
          object shpBtnAdicionar: TShape
            Left = 0
            Top = 0
            Width = 61
            Height = 61
            Align = alClient
            Brush.Color = clPurple
            Pen.Style = psClear
            Shape = stRoundRect
            ExplicitLeft = 8
            ExplicitTop = 8
            ExplicitWidth = 65
            ExplicitHeight = 65
          end
          object btnAdicionar: TSpeedButton
            Left = 0
            Top = 0
            Width = 61
            Height = 61
            Align = alClient
            Caption = '+'
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWhite
            Font.Height = -27
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ExplicitLeft = 16
            ExplicitTop = 16
            ExplicitWidth = 23
            ExplicitHeight = 22
          end
        end
        object pnlFormaPgto: TPanel
          Left = 0
          Top = 0
          Width = 506
          Height = 61
          Align = alClient
          BevelOuter = bvNone
          TabOrder = 1
          ExplicitLeft = 192
          ExplicitTop = 8
          ExplicitWidth = 185
          ExplicitHeight = 41
          object Panel4: TPanel
            Left = 0
            Top = 0
            Width = 233
            Height = 61
            Align = alLeft
            BevelOuter = bvNone
            Padding.Left = 10
            Padding.Top = 15
            Padding.Right = 10
            Padding.Bottom = 10
            TabOrder = 0
            object cbxFormaPgto: TComboBox
              Left = 10
              Top = 15
              Width = 213
              Height = 27
              Align = alClient
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -16
              Font.Name = 'Tahoma'
              Font.Style = []
              ParentFont = False
              TabOrder = 0
              Text = 'ComboBox1'
            end
          end
          object pnlEdtValor: TPanel
            Left = 233
            Top = 0
            Width = 273
            Height = 61
            Align = alClient
            BevelOuter = bvNone
            Padding.Left = 10
            Padding.Top = 15
            Padding.Right = 10
            Padding.Bottom = 20
            TabOrder = 1
            ExplicitLeft = 8
            ExplicitWidth = 233
            object edtValor: TEdit
              Left = 10
              Top = 15
              Width = 253
              Height = 26
              Align = alClient
              Alignment = taRightJustify
              BorderStyle = bsNone
              Font.Charset = DEFAULT_CHARSET
              Font.Color = clWindowText
              Font.Height = -16
              Font.Name = 'Tahoma'
              Font.Style = []
              ParentColor = True
              ParentFont = False
              TabOrder = 0
              Text = 'R$ 0,00'
              ExplicitHeight = 36
            end
          end
        end
      end
      object pnlBtns: TPanel
        Left = 10
        Top = 340
        Width = 567
        Height = 41
        Align = alBottom
        BevelOuter = bvNone
        TabOrder = 1
        ExplicitLeft = 200
        ExplicitTop = 144
        ExplicitWidth = 185
        object pnlBtnCancelar: TPanel
          Left = 0
          Top = 0
          Width = 283
          Height = 41
          Align = alLeft
          BevelOuter = bvNone
          Padding.Left = 5
          TabOrder = 0
          object shpBtnCancelar: TShape
            Left = 5
            Top = 0
            Width = 278
            Height = 41
            Align = alClient
            Brush.Color = clSilver
            Pen.Style = psClear
            Shape = stRoundRect
            ExplicitLeft = 112
            ExplicitTop = -8
            ExplicitWidth = 65
            ExplicitHeight = 65
          end
          object btnCancelar: TSpeedButton
            Left = 5
            Top = 0
            Width = 278
            Height = 41
            Align = alClient
            Caption = 'Cancelar'
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -19
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ExplicitLeft = 128
            ExplicitTop = 8
            ExplicitWidth = 23
            ExplicitHeight = 22
          end
        end
        object pnlBtnConfirmar: TPanel
          Left = 283
          Top = 0
          Width = 284
          Height = 41
          Align = alClient
          BevelOuter = bvNone
          Padding.Right = 5
          TabOrder = 1
          ExplicitLeft = 192
          ExplicitWidth = 185
          object shpBtnConfirmar: TShape
            Left = 0
            Top = 0
            Width = 279
            Height = 41
            Align = alClient
            Brush.Color = clPurple
            Pen.Style = psClear
            Shape = stRoundRect
            ExplicitLeft = 5
          end
          object btnConfirmar: TSpeedButton
            Left = 0
            Top = 0
            Width = 279
            Height = 41
            Align = alClient
            Caption = 'Confirmar'
            Flat = True
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWhite
            Font.Height = -19
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            ExplicitLeft = 128
            ExplicitTop = 8
            ExplicitWidth = 23
            ExplicitHeight = 22
          end
        end
      end
      object pnlFormasPgto: TPanel
        Left = 10
        Top = 81
        Width = 567
        Height = 259
        Align = alClient
        BevelOuter = bvNone
        TabOrder = 2
        ExplicitLeft = 200
        ExplicitTop = 144
        ExplicitWidth = 185
        ExplicitHeight = 41
        object ListBox1: TListBox
          Left = 0
          Top = 0
          Width = 567
          Height = 259
          Align = alClient
          BorderStyle = bsNone
          ParentColor = True
          TabOrder = 0
          ExplicitHeight = 194
        end
      end
    end
  end
end
