object PageMensagem: TPageMensagem
  Left = 0
  Top = 0
  AlphaBlend = True
  AlphaBlendValue = 240
  BorderStyle = bsNone
  ClientHeight = 748
  ClientWidth = 1202
  Color = clBackground
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Tahoma'
  Font.Style = []
  OnShow = FormShow
  TextHeight = 16
  object pnlContainer: TPanel
    AlignWithMargins = True
    Left = 192
    Top = 168
    Width = 400
    Height = 170
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    BevelOuter = bvNone
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentBackground = False
    ParentFont = False
    TabOrder = 0
    object pnlTitulo: TPanel
      Left = 0
      Top = 0
      Width = 400
      Height = 41
      Align = alTop
      BevelOuter = bvNone
      Caption = 'T'#237'tulo'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      object imgMensagem: TImage
        Left = 0
        Top = 0
        Width = 40
        Height = 41
        Align = alLeft
        Stretch = True
      end
    end
    object pnlBtns: TPanel
      Left = 0
      Top = 129
      Width = 400
      Height = 41
      Align = alBottom
      BevelOuter = bvNone
      Padding.Left = 5
      Padding.Right = 5
      TabOrder = 1
      object pnlBtnCancelar: TPanel
        Left = 5
        Top = 0
        Width = 100
        Height = 41
        Align = alLeft
        BevelOuter = bvNone
        TabOrder = 0
        Visible = False
        object shpBtnCancelar: TShape
          Left = 0
          Top = 0
          Width = 100
          Height = 41
          Align = alClient
          Pen.Style = psClear
          Shape = stRoundRect
          ExplicitLeft = 16
          ExplicitTop = -8
          ExplicitWidth = 65
          ExplicitHeight = 65
        end
        object btnCancelar: TSpeedButton
          Left = 0
          Top = 0
          Width = 100
          Height = 41
          Align = alClient
          Caption = 'Cancelar'
          Flat = True
          OnClick = btnCancelarClick
          ExplicitLeft = 40
          ExplicitTop = 8
          ExplicitWidth = 23
          ExplicitHeight = 22
        end
      end
      object pnlBtnConfirmar: TPanel
        Left = 295
        Top = 0
        Width = 100
        Height = 41
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 1
        Visible = False
        object shpBtnConfirmar: TShape
          Left = 0
          Top = 0
          Width = 100
          Height = 41
          Align = alClient
          Pen.Style = psClear
          Shape = stRoundRect
          ExplicitLeft = 16
          ExplicitTop = -8
          ExplicitWidth = 65
          ExplicitHeight = 65
        end
        object btnConfirmar: TSpeedButton
          Left = 0
          Top = 0
          Width = 100
          Height = 41
          Align = alClient
          Caption = 'Confirmar'
          Flat = True
          OnClick = btnConfirmarClick
          ExplicitLeft = 40
          ExplicitTop = 8
          ExplicitWidth = 23
          ExplicitHeight = 22
        end
      end
      object pnlBtnOk: TPanel
        Left = 195
        Top = 0
        Width = 100
        Height = 41
        Align = alRight
        BevelOuter = bvNone
        TabOrder = 2
        Visible = False
        object shpBtnOk: TShape
          Left = 0
          Top = 0
          Width = 100
          Height = 41
          Align = alClient
          Pen.Style = psClear
          Shape = stRoundRect
          ExplicitLeft = 16
          ExplicitTop = -8
          ExplicitWidth = 65
          ExplicitHeight = 65
        end
        object btnOk: TSpeedButton
          Left = 0
          Top = 0
          Width = 100
          Height = 41
          Align = alClient
          Caption = 'OK'
          Flat = True
          OnClick = btnOkClick
          ExplicitLeft = 40
          ExplicitTop = 8
          ExplicitWidth = 23
          ExplicitHeight = 22
        end
      end
    end
    object pnlMensagem: TPanel
      Left = 0
      Top = 41
      Width = 400
      Height = 88
      Align = alClient
      BevelOuter = bvNone
      TabOrder = 2
      object memMensagem: TMemo
        AlignWithMargins = True
        Left = 3
        Top = 3
        Width = 394
        Height = 82
        Align = alClient
        BorderStyle = bsNone
        ReadOnly = True
        TabOrder = 0
      end
    end
  end
end
